FeedbackApp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name = 'FeedbackApp'

urlpatterns = [
	path('HasilFeedback', views.index),
	path('', views.create, name='create'),	
	path('admin/', admin.site.urls),
]

TestimonyApp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'TestimonyApp'

urlpatterns = [
    path('', views.index, name='index'),
]

inputMakananApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'inputMakananApp'

urlpatterns = [
    path('', views.inputan, name='inputan'),
    path('outputkalori/', views.outputkalori, name='outputkalori'),
    path('horey/', views.horey, name='horey'),
    path('tambahMakanan/', views.tambahMakanan, name='tambahMakanan'),
]

tugasKelompok/urls.py
from django.urls import path, include
from django.contrib import admin

#from . import views

urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include('tugasKelompokApp.urls')),
    path('HasilFeedback/', include('FeedbackApp.urls')),
    path('homepage/', include('tugasKelompokApp.urls')),
    #path('HasilFeedback/', include('FeedbackApp.urls')),
    path('admin/', admin.site.urls),
    path('testimony/', include('TestimonyApp.urls')),
    path('inputMakananApp/', include('inputMakananApp.urls')),
]

tugasKelompokApp/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *

app_name = 'tugasKelompokApp'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('homepage/', homepage, name="homepage"),
    path('submitisibuku/', submitIsiBuku, name="submitisibuku"),
    path('IsiFeedback/', include('FeedbackApp.urls')),
    path('admin/', admin.site.urls),
    path('testimony/', include('TestimonyApp.urls')),
 	path('inputMakananApp/', include('inputMakananApp.urls')),
]

#
#from django.contrib import admin
#from django.urls import path, include
#from . import views

#urlpatterns = [
#    path('admin/', admin.site.urls),
#    path('', include('tugasKelompokApp.urls')),
#    path('HasilFeedback/', include('FeedbackApp.urls')),
#]

FeedbackApp/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class ModelFeedback(models.Model):
	Nama	= models.CharField(max_length=50)
	Pesan	= models.TextField()

TestimonyApp/models.py
from django.db import models

class ModelTestimony(models.Model):
    nama = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)
    kesan = models.CharField(max_length=150)

inputMakananApp/models.py
from django.db import models

class listMakanan(models.Model):
    menuUtama = models.CharField(max_length=255)
    lauk = models.CharField(max_length=255)
    sayur = models.CharField(max_length=255)


    def __str__(self):
        return self.namaKegiatan   

class kaloriMakanan(models.Model):
    kaloriMenuMakanan = models.IntegerField()

    def __str__(self):
        return self.kaloriMenuMakanan   

tugasKelompokApp/models.py
from django.db import models

# Create your models here.

class IsiBukuTamu(models.Model):
 	nama = models.CharField(max_length=30, default = '')
 	email = models.CharField (max_length=30, default = '')
 	tanggal = models.CharField (max_length=100, default = '')
 	

FeedbackApp/forms.py
from django import forms
from .models import ModelFeedback
from django.forms import ModelForm, TextInput

class FormFeedback(forms.ModelForm):
	class Meta(object):
		model = ModelFeedback
		fields = [
			'Nama',
			'Pesan',
		]
		widgets = {
			'Nama': TextInput(),
			'Pesan': TextInput(),
		}

TestimonyApp/forms.py
from django import forms
from .models import ModelTestimony

class FormTestimony(forms.ModelForm):
    class Meta(object):
        model = ModelTestimony
        fields = [
            'nama', 
            'email', 
            'kesan',
        ]
        

inputMakananApp/forms.py
from django import forms

class formMakanan(forms.Form):
    menuUtama = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control', 'placeholder' : 'Menu utama', 'id' : 'menuUtama'}))
    lauk = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw','class' : 'form-control', 'placeholder' : 'Lauk', 'id' : 'lauk'}))
    sayur = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw','class' : 'form-control', 'placeholder' : 'Sayur', 'id' : 'sayur'}))

tugasKelompokApp/forms.py
from django import forms

class IsiBukuTamuForm(forms.Form):
 	nama = forms.CharField (max_length=30)
 	email = forms.CharField (max_length=30)
 	tanggal = forms.CharField (max_length=100)

FeedbackApp/views.py
from django.shortcuts import render, redirect
from .forms import FormFeedback
from .models import ModelFeedback

# Create your views here.
def index(request):
	modelFeedback = ModelFeedback.objects.all()
	context = {
		'hasilFeedback' : modelFeedback,
	}

	return render(request, 'OutputSaran.html', context)

def create(request):
	formFeedback = FormFeedback(request.POST or None)	# request.POST buat validasi

	# Masukin dari form ke database
	if request.method == 'POST':
		if formFeedback.is_valid():	# Kalau input valid
			formFeedback.save()
			
			return redirect('/IsiFeedback/HasilFeedback')	# Abis ngisi form redirect ke halaman schedule

	context = {
		'formFeedback' : formFeedback,
	}

	return render(request, 'InputSaran.html', context)

TestimonyApp/views.py
from django.shortcuts import render,redirect
from .forms import FormTestimony
from .models import ModelTestimony
# Create your views here.

def index(request):
    modelTestimony = ModelTestimony.objects.all()
    context = {
        'hasilTestimony' : modelTestimony
    }
#    return render(request, 'testimony.html', context)

#def show(request):
    if request.method == 'POST':
        form = FormTestimony(request.POST)
        if form.is_valid():
            nama = request.POST['nama']
            email = request.POST['email']
            kesan = request.POST['kesan']
            addTestimony = ModelTestimony(nama=nama, email=email, kesan=kesan)
            addTestimony.save()
#    return redirect('/testimony/')
    return render(request, 'testimony.html', context)

inputMakananApp/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .forms import formMakanan
from .models import listMakanan, kaloriMakanan

def inputan(request):
    list_makanan = listMakanan.objects.order_by('id')
    list_ngasal = kaloriMakanan.objects.order_by('id')
    form = formMakanan()
    context = {'list_makanan' : list_makanan, list_ngasal : 'list_ngasal', 'form' : form}
    return render(request, 'inputan.html', context)

def outputkalori(request):
	return render(request,'outputkalori.html')

def horey(request):
	return render(request,'horey.html')

@require_POST
def tambahMakanan(request):
    form = formMakanan(request.POST)

    makananBaru = listMakanan(menuUtama = request.POST['menuUtama'], lauk = request.POST['lauk'], sayur = request.POST['sayur'])
    makananBaru.save()
    kaloriNgasal = kaloriMakanan(kaloriMenuMakanan = 20)
    kaloriNgasal.save()

    return redirect('inputMakananApp:outputkalori')

tugasKelompokApp/views.py
from django.shortcuts import render, redirect
from .forms import IsiBukuTamuForm
from .models import IsiBukuTamu

def index(request):
    return render(request, 'HelloWorld.html')

def homepage(request):
    listBuku = IsiBukuTamu.objects.all().values()
    return render(request, 'index.html', {'list' : listBuku})

def submitIsiBuku (request):
	if request.method == 'POST':
		form = IsiBukuTamuForm(request.POST)
		if form.is_valid():
			print ("hello")
			nama = request.POST ['nama']
			email = request.POST['email']
			tanggal = request.POST ['tanggal']
			submit = IsiBukuTamu(nama=nama, email=email, tanggal=tanggal)
			submit.save()
	return redirect('/inputMakananApp/')

FeedbackApp/templates/InputSaran.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <title>Masukan Untuk Kami</title>
  </head>
  <body style="background-image: url({% static 'assets/isibuku.jpg' %}); width: 110%; height: 100%; background-size: cover;">
    <div class="row">
      <div class="col">
        <div class="row" style="background-color: #00CED1; position: fixed; width: 110%;">


              <div class="col" style="font-size: 35px">
                <img src="{% static 'assets/bg.png' %}" style="width: 6%; height: 100%; border-radius: 30%;">
                <span class="whiteText">Calorie</span>&nbsp;<span class="blackText" style="font-weight: bold;">Ku</span>
              </div>


        </div>

        <div class="row" style="text-align: center;margin-left: 20%; margin-right: 20%; float: center; border-radius: 10%;">
          <div class="container-fluid">
            <br>
            <div class="pertanyaan" style="font-size: 48px;"> 
              <br><br>Ada Saran Untuk Kami? <br> </div>
              <div class="box" style="padding: 35%; padding-top: 5%; padding-bottom: 2%; align-self: center;">
              <form method="post" style="font-size:24px; font-style: italic; font-family: Merriweather;font-weight: bold;">
                {% csrf_token %}

                <div class="fontForm" style="float: left;">Nama: </div>
                <br>
                {{ formFeedback.Nama }} <br>
                <div class="fontForm" style="float: left;">Pesan: </div>
                <br>
                {{ formFeedback.Pesan }}

                
                <button type="Submit" class="btn btn-primary butt" style="margin-top: 8%;">Submit</button>
              </form>
              </div>
          </div>
        </div>

      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

FeedbackApp/templates/OutputSaran.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <title>List Masukan Untuk Kami</title>
  </head>
  <body style="background-color: white;">

    <div class="row">
      <div class="col">
        <div class="row" style="background-color: #00CED1; position: fixed; width: 110%;">


              <div class="col" style="font-size: 35px">
                <img src="{% static 'assets/bg.png' %}" style="width: 6%; height: 100%; border-radius: 30%;">
                <span class="whiteText">Calorie</span>&nbsp;<span class="blackText" style="font-weight: bold;">Ku</span>
              </div>


        </div>

        <div class="row" style="text-align: center;">
          <div class="container-fluid">
            <br><br><br><br>
            <div class="pertanyaan" style="font-size: 48px;">Saran Untuk Kami</div>
            <br>
            <div class="counter">
            <table class="table">
              <thead style="border-bottom: 4px solid #00CED1; width: 100%;">
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Pesan</th>
                </tr>
              </thead>

            <tbody>
            {% for Feedback in hasilFeedback %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <th scope="row">{{ Feedback.Nama }}</th>
              <th scope="row">{{ Feedback.Pesan }}</th>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>



          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

TestimonyApp/templates/testimony.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Testimoni</title>
    </head>

    <body>
        <div class="row">
      <div class="col">
        <div class="row" style="background-color: #777D71; padding: 0.5%;">

              <div class="col-auto">
                <div id="circle"></div>
              </div>
              <div class="col" style="font-size: 35px">
                <span class="whiteText">Calorie</span>&nbsp;<span class="greenText">Ku</span>
              </div>

        </div>

        <div class="box" style="padding: 20%; padding-top: 5%; padding-bottom: 0%; align-self: center;">
        <form method="POST" action="/testimony/" style="font-size:24px; font-style: italic; font-family: Merriweather;">
            {% csrf_token %}
            <h3 align="center">Tulis Testimoni yuk!</h3>
            <div class="form-group">
                <label>Nama</label>
                <input type="text" class="form-control" position="absolute" name="nama" maxlength="50" id= "nama" placeholder="Nama">
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="text" class="form-control" position="absolute" name="email" maxlength="50" id= "email" placeholder="Email">
            </div>
            <div class="form-group">
                <label>Kesan</label>
                <textarea type="text" class="form-control" position="absolute" name="kesan" maxlength="200" rows="4" id="kesan"></textarea>
            </div>
            <button position="absolute" align="center" type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>


    {% for index in hasilTestimony %}
            <br>
            Nama :
            {{ index.nama }} <br>
            Email :
            {{ index.email }} <br>
            Kesan :
            {{ index.kesan }} <br>
            
    {% endfor %}
    </body>
</html>

inputMakananApp/templates/horey.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HORE!!!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body style="background-color: #B6D4AE;">

    <div class="m-5" style="text-align: center;">    
        <p>HOREEYY.</p>
        <p>Asupan kalori kamu sudah ideal.</p>
        <p>Jaga terus yaa porsi makannya</p>
        <p>^^</p>
        <a href="{% url 'FeedbackApp:create' %}"><button style="font-size: 1vw" class="btn btn-primary ">Saran</button></a>
    <a href="{% url 'TestimonyApp:index' %}"><button style="font-size: 1vw" class="btn btn-primary ">Testimoni</button></a>
    </div>

<<<<<<< HEAD
    <a href="/IsiFeedback"><button style="font-size: 1vw" class="btn btn-danger ">Saran</button></a>
    <a href="/testimony"><button style="font-size: 1vw" class="btn btn-danger ">Testimoni</button></a>
=======
    

>>>>>>> a784c6934c4ad0cebd891abd144c7645ea0fcaf2
</body>
</html>

inputMakananApp/templates/inputan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Input Makanan</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <style>
    body{
        background-repeat: no-repeat;
        height: 100%; 
        background-position: center;
        background-size: cover;
    }
    .ok{align-content: center;}
    </style>
</head>
<body background = "{% static 'images/1571486125145.jpg' %}" >
    <div class=" d-flex justify-content-center">
    <div style="margin: 15%; margin-top: 5%;" class="card-body bg-light" style="width: 80%;">
        <h1 style="font-size: 4.8vw; text-align: center;" class="ok">Makan apa aja hari ini?</h1><br>
        <div style="margin: 10%;margin-top: 5%; margin-bottom: 5%;">
        <form method="POST" action="{% url 'inputMakananApp:tambahMakanan' %}">
            {% csrf_token %}

            <div>
                <h2 style="font-size: 2.4vw"class="">Sarapan</h2>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Menu utama</label>
                    {{ form.menuUtama }}
                </div>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Lauk</label>
                    {{ form.lauk }}
                </div>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Sayur</label>
                    {{ form.sayur }}
                </div>
            </div>

            <div>
                <h2 style="font-size: 2.4vw"class="">Makan siang</h2>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Menu utama</label>
                    {{ form.menuUtama }}
                </div>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Lauk</label>
                    {{ form.lauk }}
                </div>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Sayur</label>
                    {{ form.sayur }}
                </div>
            </div>

            <div>
                <h2 style="font-size: 2.4vw"class="">Makan malam</h2>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Menu utama</label>
                    {{ form.menuUtama }}
                </div>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Lauk</label>
                    {{ form.lauk }}
                </div>
                <div class="form-group">
                    <label style="font-size: 1vw" for="" class="">Sayur</label>
                    {{ form.sayur }}
                </div>
                <button style="font-size: 1vw" type="submit" class="btn-primary">Hitung</button>
            </div>
            </div>
        </form>
    </div>
</div>
    </body>
</html>

inputMakananApp/templates/outputkalori.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jumlah kalori</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <style>
        body{
        background-repeat: no-repeat;
        height: 100%; 
        background-position: center;
        background-size: cover;
    }
    </style>
</head>
<body background = "{% static 'images/1571486125145.jpg' %}" >
    <div style="margin: 15%; margin-top: 5%;" class="card-body bg-light" style="width: 80%;">
    <h1>Kalorimu hari ini adalah</h1>
    <ul class="list-group">

            <li class="list-group-item">Sarapan     : 20 kalori</li>
            <li class="list-group-item">Makan siang : 20 kalori</li>
            <li class="list-group-item">Makan malam : 20 kalori</li>
            <li class="list-group-item">Total       : 60 kalori</li>
   </ul>
    <a href="{% url 'inputMakananApp:horey' %}"><button style="font-size: 1vw"class="btn-primary">Lihat saran</button>
    </a>
    </div>

</body>
</html>

tugasKelompokApp/templates/HelloWorld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tugas Kelompok Hello World</title>
</head>
<body>
    Hello World!
    <a href="IsiFeedback/"> Isi Feedback </a>
</body>
</html>